android/src/main/AndroidManifest.xml
android/src/main/java/com/thebluealliance/androidclient/activities/BaseActivity.java
android/src/main/java/com/thebluealliance/androidclient/background/PopulateNotificationDashboard.java
android/src/main/java/com/thebluealliance/androidclient/eventbus/NotificationsUpdatedEvent.java
android/src/main/java/com/thebluealliance/androidclient/fragments/NotificationDashboardFragment.java
android/src/main/java/com/thebluealliance/androidclient/gcm/GCMMessageHandler.java
android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/AllianceSelectionNotification.java
android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/AwardsPostedNotification.java
android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/BaseNotification.java
android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/CompLevelStartingNotification.java
android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/DistrictPointsUpdatedNotification.java
android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/GenericNotification.java
android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/ScheduleUpdatedNotification.java
android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/ScoreNotification.java
android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/SummaryNotification.java
android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/UpcomingMatchNotification.java
android/src/main/java/com/thebluealliance/androidclient/listeners/NotificationDismissedListener.java

Fix #382 auto-update Recent Notifications when a notification arrives (using EventBus).
Fix #384 Notifications Not Being Marked As Read.
Fix double-chime notifications.
Fix navigating Back to Recent Notifications should refresh in case notifications arrived while it was paused.
Tapping a summary notification will reuse the Recent Notifications if it's on top rather than add a confusing entry to the task stack.
Refactor replicatedcode into BaseNotification.getBaseBuilder() where it can uniformly mark the content intents as "from notifications" so the receiving activity can tell when to dismiss "read" notifications.
_Branched from notification-titles which was merged from master, so there may be some commits from master to revert. If that turns out to be problematic, I can back out the …

Notification activity updates

---

android/build.gradle
android/src/debug/res/values/strings.xml
android/src/main/AndroidManifest.xml
android/src/main/res/values/strings.xml

Play Store doesn't like debug/release string resources for enabling GCM
testing in debug builds, so do it instead via Manifest Merger placeholders.
Changing this setting in build.gradle does work although I can't build a
release config to verify there.

Fix #392 Notification Testing Script Temporarily Disabled

---

android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/SummaryNotification.java
android/src/main/res/values/strings_notification.xml

Limit the summary list to 7 items to work around an Android 5.1 bug and
generally avoid taking up the whole notification shade.
(No hurry to push this to production.)

Fix #412 Summary notification shows "@17041057" after 7 items

---

android/src/main/java/com/thebluealliance/androidclient/views/MatchView.java

This distinguishes today's matches from tomorrow's matches and from
yesterday's matches with delayed results (e.g. right now on Carson and
Tesla).
I tried out two approaches. This simple, low-risk approach just prepends
the day-of-week to the formatted time. Would any locales rather append the
day-of-week?
The other approach uses the user's 12/24 hour preference to select the date
format pattern "E HH:mm" or "E hh:mm a" from a string resource, calls
DateFormat.getBestDateTimePattern() on API level >= 18 to allow
locale-specific adjustments and field reorderings, then uses that to format
the Date. Localizing those resources might fight with
getBestDateTimePattern(), so maybe the code should use one of those two.
The app isn't really internationalized yet so the added complexity doesn't
pay …

Fix #406 show the day-of-week with each match time

---

android/build.gradle
android/src/main/java/com/thebluealliance/androidclient/activities/ViewTeamActivity.java
android/src/main/java/com/thebluealliance/androidclient/modules/DatafeedModule.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/YearsParticipatedDropdownSubscriber.java
android/src/test/java/com/thebluealliance/androidclient/subscribers/YearsParticipatedDropdownSubscriberTest.java

Fixes #459 so that years are now ordered in reverse chronological order.
I also moved around some of the stuff that deals with year selection. This slightly improves separations of concerns.

Fixes #459; improves behavior of team year selection

---

.travis.yml
android/build.gradle
android/src/main/java/com/thebluealliance/androidclient/activities/settings/SettingsActivity.java
android/src/main/java/com/thebluealliance/androidclient/fragments/NavigationDrawerFragment.java

Before, if you clicked to enable myTBA in settings but then canceled it, the preference switch would show that myTBA was enabled until the next time the settings activity was recreated. Now, the PreferenceFragment driving everything will check if myTBA is enabled in onResume and update the UI to reflect that.
This also targets API23 (Marshmallow) and bumps build tools, the support libraries, and Play Services to their latest respective versions.

Fix myTBA preference, bump platform/libarary versions

---

android/src/main/res/layout/activity_gameday.xml
android/src/main/res/layout/activity_mytba_model_settings.xml
android/src/main/res/values-v21/dimens.xml

This should fix the weird FAB layout behavior we were seeing on 4.x devices. It turns out that if FABs are placed as a direct child of a CoordinatorLayout, the CL will translate the FAB to account for the extra padding that's added on 4.x devices to allow for the shadow. So, we still have to provide a margin for the FAB.
People with 4.x devices, please test this! I was able to test 2/3 activities with FABs, but not the myTBA settings activity that's launched from the myTBA fav/sub lists (I was running on an emulator where I couldn't enable myTBA).

FAB layout fixes

---

android/src/main/java/com/thebluealliance/androidclient/datafeed/DatafeedModule.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/status/TBAStatusController.java

Because users who aren't logged in won't receive GCM notifications of status updates, we should poll more frequently.
This also sets a separate timeout for showing the "Please upgrade" dialog (we don't want to spam users with that). I would almost feel comfortable making that last days or even weeks. We want to remind users that a new version is available, but don't want to annoy them by asking too frequently. In that case, the "last shown" time should be a persistent preference that will last across application restarts.

Reduces status rate limiting for users who are not logged in

---

android/src/main/java/com/thebluealliance/androidclient/Utilities.java
android/src/main/java/com/thebluealliance/androidclient/activities/BaseActivity.java
android/src/main/java/com/thebluealliance/androidclient/activities/HomeActivity.java
android/src/main/java/com/thebluealliance/androidclient/activities/OnboardingActivity.java
android/src/main/java/com/thebluealliance/androidclient/activities/RedownloadActivity.java
android/src/main/java/com/thebluealliance/androidclient/activities/ViewTeamActivity.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/status/TBAStatusController.java
android/src/main/java/com/thebluealliance/androidclient/fragments/event/EventStatsFragment.java
android/src/main/java/com/thebluealliance/androidclient/fragments/mytba/MyTBAFragment.java

This brings nice Material dialogs to pre-Lollipop devices.
Shoutout to the Android team for making this stupidly easy to do.

Switch to using the Support Library dialogs

---

README.md

http://shields.io/ provides nice standardized status badges, and they have a pretty flat design too. Unfortunately waffle.io doesn't adhere to the badge spec, so those badges look a litle out of place right now.

Use status badges from shields.io

---

android/src/main/java/com/thebluealliance/androidclient/listitems/RankingListElement.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/RankingsListSubscriber.java
android/src/test/java/com/thebluealliance/androidclient/subscribers/RankingsListSubscriberTest.java
android/src/test/resources/2015necmp_rankings.json
android/src/test/resources/2015ohri_rankings.json

This just treats the team number as a generic string instead of explicitly as an integer, which is fine because the integer value is never used for comparisons or anything.

Change event rankings to properly handle ####B team numbers. Fixes #530.

---

android/build.gradle

There is an active issue in the Google Play Service Analytics library where a Provider com.google.android.gms.measurement.AppMeasurementContentProvider is being defined in all android applications which use this library unless defaultConfig.applicationId is defined
https://code.google.com/p/analytics-issues/issues/detail?id=784
This simple addition to the build.gradle is supposed to fix this issue and stop some users from getting the -505 error from the Google Play Store while installing the app when another app also using the Google Play Service Analytics Library without setting the defaultConfig.applicationId is already installed.
For instance I have the AMC Theaters application installed on my phone, today I wanted to install The Blue Alliance, logcat showed a warning with the …

Workaround Google Play Service Analytics issue 784

---

android/src/main/java/com/thebluealliance/androidclient/database/tables/EventTeamsTable.java
android/src/main/java/com/thebluealliance/androidclient/database/tables/EventsTable.java

Turns out this issue was being caused by an overly-inclusive JOIN statement. We were selecting all the columns from both the Events and EventTeams table, both of which contained a "key" column. When the ModelInflater tried to use the EventTeams key as an Event model key, everything broke, and the rest is history. The fix was to only select the columns from the Events table.
This doesn't explain why EventTeams don't seem to be cached all the time, but that's another issue for another day.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/547)

Fixes #545

---

scripts/test_notification.py

I was working with the python scripts a bit when my OCD kicked in and I decided to make naming and formatting more consistent.
I also ended up adding some additional options to the `ping` and `broadcast` commands to make it easier to test them with different URLs or without a URL at all. The URL has a nice default.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/558)

Updated py script formatting and naming for consistency

---

android/src/main/java/com/thebluealliance/androidclient/fragments/RecentNotificationsFragment.java

Makes the Recent Notifications list pretty again. Instead of defining the necessary stuff in XML, we just override it programmatically to avoid having to create another subclass of DatafeedFragment. Yay code reuse!
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/556)

Fixes #552

---

android/src/main/java/com/thebluealliance/androidclient/Utilities.java
android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/GenericNotification.java

If for some reason we want to direct users to a non-TBA URL via a ping or broadcast notification, we can now do that! This simply passes off any URL not in the thebluealliance.com domain to a generic View intent, which will fire off the approriate app/browser.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/559)

Enable generic URLs for ping/broadcast notifications

---

android/src/main/java/com/thebluealliance/androidclient/activities/LaunchActivity.java
android/src/main/java/com/thebluealliance/androidclient/database/writers/EventTeamAndTeamListWriter.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/DatafeedModule.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/combiners/TeamAndEventTeamCombiner.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/deserializers/APIStatusDeserializer.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/status/TBAStatusController.java
android/src/main/java/com/thebluealliance/androidclient/models/APIStatus.java
android/src/test/java/com/thebluealliance/androidclient/datafeed/deserializers/APIStatusDeserializerTest.java
android/src/test/resources/api_status.json

Caching is hard...
The issue in the screenshot happened because the original event was deleted on the server and the new response was in OkHttp's cache, but it never registered as needing to update in the app's db. I was able to fix it by clearing my local data, but that's not a scalable solution. So I added a timestamp to the TBAStatus model. We can set a timestamp server side and each app will clear its local cache exactly once after that (tracked via "last clear" timestamp stored in sharedPrefs). We'll also clear the cache on app updates, just to try and avoid things getting stuck in it.
Fixes #546 
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/549)

Fix Caching Issues

---

android/src/main/java/com/thebluealliance/androidclient/adapters/ExpandableListViewAdapter.java
android/src/main/java/com/thebluealliance/androidclient/adapters/MatchListAdapter.java
android/src/main/java/com/thebluealliance/androidclient/binders/ExpandableListViewBinder.java
android/src/main/java/com/thebluealliance/androidclient/binders/ListViewBinder.java
android/src/main/java/com/thebluealliance/androidclient/binders/TeamTabBinder.java

As best as I can tell, this fixes #544. The fix ended up relating to how data was bound to lists. We used to create a new adapter every time we got new data; setting that new adapter to the list would wipe any scroll state the list had. Now, we reuse the existing adapter, swap in the new data, and tell the adapter its data has changed. The system handles the rest, and everyone is happy.
Also fixes a related bug where the main teams list would reset to the top of the first tab whenever it was resumed. This is also caused by swapping in a new adapter when none is needed. Now, a new adapter is only created a) on the first data update, and b) if the number of tabs changes.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on …

Fixes #544 (lists scroll to top

---

android/src/main/java/com/thebluealliance/androidclient/background/firstlaunch/LoadTBAData.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/retrofit/APIv2.java

Instead of hacking around with the reactive versions, do things properly
and add a new declaration that uses the Call<> response. Now we can
ensure that the response was successful and handle the situation
accordingly.
Tested by going Debug Settings -> Redownload Data and putting my phone in airplane mode while it's loading things. Ensured we caught the responses erroring:
Fixes #562 via proper error handling
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/569)

Refactor LoadTBAData to use Synchronous Retrofit

---

android/src/main/java/com/thebluealliance/androidclient/eventbus/EventStatsEvent.java
android/src/main/java/com/thebluealliance/androidclient/listitems/StatsListElement.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/StatsListSubscriber.java
android/src/test/java/com/thebluealliance/androidclient/subscribers/StatsListSubscriberTest.java

Also updates test coverage to make sure we're posting the right string
to the eventbus :)
All better...
Fixes #568
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/570)

Show Team Number in Event Top OPRs

---

android/src/main/java/com/thebluealliance/androidclient/binders/ListViewBinder.java
android/src/main/java/com/thebluealliance/androidclient/fragments/DatafeedFragment.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/BaseAPISubscriber.java

It seems like that references to views in the binder were going away
after leaving/coming back to the screen, so it's probably the framework
recreating instances.
BaseAPISubscriber.hasBinderBound is sticky, we we want to reset it when
the parent fragment is stopped so we rebind ButterKnife (and potentially
do other things in the future) if/when we come back.
Fixes #565
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/571)

Rebind ButterKnife after parent activity stop

---

scripts/test_notification.py

Added two commands to test_notification.py to facilitate testing
*  `spam`: sends an arbitrary number of random notifications to the app; defaults to 4, but the count can be specified with the `--count` flag
* `all`: sends one of each notification type to the app
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/572)

Improvements to test_notification.py

---

android/src/main/res/values/styles.xml

When I wrapped the team info stuff in cards, I forgot to account for the 8dp margin around the cards. This PR realigns the text in the cards with the 72dp keyline, because #materialyolo
Before:
After:
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/573)

Realigns text on the "info" pages to the 72dp keyline

---

android/src/main/java/com/thebluealliance/androidclient/fragments/FirebaseTickerFragment.java

If the ticker contains fewer elements than the existing buffer size,
then it'll hang forever waiting for enough items to come through and
fill the buffer.
Buffering is requried since we're pushing items into the Observable at
"for loop" speed, so we need to be able to slow down the processing (see
ResumableRxFirebase).
This now puts a time limit on the buffers, see
http://reactivex.io/RxJava/javadoc/rx/Observable.html#buffer%28long,%20java.util.concurrent.TimeUnit,%20int%29
The main downside is the onNext callback is executed every `period` of
time (with empty data). This commit has it at every 5 seconds - also the
max initial loading time. Not sure what the perf implications are.
Can some other people test this out before I merge and see if it affects
perf? It seems like it does to me, …

Fix buffering for Firebase tickers

---

android/src/main/java/com/thebluealliance/androidclient/activities/HomeActivity.java
android/src/main/java/com/thebluealliance/androidclient/binders/EventTabBinder.java
android/src/main/java/com/thebluealliance/androidclient/fragments/EventsByWeekFragment.java

HomeActivity was always telling us to start at tab 0 even when we
weren't restoring instance state. Instead, tell to start at -1, which we
can then use to determine ourselves which tab is for the current week
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/579)

Fix auto week tab selection

---

android/src/main/res/layout/list_view_with_spinner.xml

Long story short, if a `ListView` isn't absolutely sized (e.g. size specified in dps or `match_parent`), it has to call `getView()` on all the items in the list view several times to properly determine its size, which is actually really expensive. By telling the `ListView` how big it should be in terms of its parent view, we cut that down a lot, which makes things much more performant. Yay!
Measuring jank is hard, so I don't have any numbers to prove this improves the UX, but a great way to see this in action is to swipe really fast through the 2016 event tabs in this branch and compare it to prod. At least on my N5, the difference was remarkable.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/th …

Major improvement to performance

---

android/src/main/java/com/thebluealliance/androidclient/binders/EventTabBinder.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/YearsParticipatedDropdownSubscriber.java
android/src/test/java/com/thebluealliance/androidclient/subscribers/YearsParticipatedDropdownSubscriberTest.java

Otherwise, when we have network errors, an
OnErrorNotImplementedException will be thrown, which we don't want.
Fixes #589
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/594)

Add onError to YearsParticipatedDropdwnSubscriber

---

android/src/main/res/values/strings_notification.xml

Brings some more consistency and readability to the notification texts.
* All notifications start with their associated event keys
* Things are consistently capitalized and punctuated
* Redundant "Event"/"Match" labels were removed
Fixes #583 
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/596)

Make notification text more consistent and readable

---

android/src/main/java/com/thebluealliance/androidclient/subscribers/TeamAtEventSummarySubscriber.java

We would erronously report every member of an alliance as the captian
when we don't have alliance data. This is because we set the wrong
default. Meh.
Fixes #605
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/612)

Fix team@event summary captain bug

---

android/src/main/java/com/thebluealliance/androidclient/activities/MyTBASettingsActivity.java
android/src/main/java/com/thebluealliance/androidclient/activities/ViewEventActivity.java
android/src/main/java/com/thebluealliance/androidclient/adapters/ViewEventFragmentPagerAdapter.java

TL;DR things work more betterer now
Steps to reproduce original issue:
* Open an event activity
* Receive a match results notification; click it to be deep-linked to the match activity
* Click up; if the event activity that was previously on top of the activity stack was of a different event, the activity would either not be updated with the info of the event that should be shown (that of the match activity that was just navigated from) or it would crash completely. Oops.
The crash was caused by the fact that `onNewIntent` is called before `onResume`, so the view hierarchy may not have been ready to manipulate. When we tried to close the myTBA settings panel if it was open from `onNewIntent`, the app could crash when the animators for that were started.
The bug where the activity wouldn't …

Fixed crash/bug introduced when I fixed match up/back navigation

---

android/build.gradle
android/src/main/java/com/thebluealliance/androidclient/datafeed/DatafeedModule.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/retrofit/FirebaseAPI.java
android/src/main/java/com/thebluealliance/androidclient/fragments/FirebaseTickerFragment.java
build.gradle

With the way things were being done before, we were accidentally loading the entire Firebase notifications node into memory, which, because of how much data there was, resulted in ~170MB of allocations, not to mention a whole lot of data use. We had to load the whole node to count how many notifications there were so we could decide if we should show the "ticker empty" message or not.
We now use Firebase's REST API to attempt to fetch a single record from the target node. If that record does not exist, we know that we need to show the no data view. That network call has pretty low overhead (2-4KB response, 50-200ms to complete, according to Postman). This results in things loading and displaying much faster.
This does not solve the issue of the UI lagging when the ticker list is being …

Fixed issue with Firebase memory

---

android/src/main/java/com/thebluealliance/androidclient/datafeed/refresh/RefreshController.java

`HomeActivity` would crash if you clicked a menu item while refreshing was disabled (and the refresh menu item didn't exist).
Fixes #624
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/626)

Added null check for menu item in RefreshController

---

android/src/main/java/com/thebluealliance/androidclient/Utilities.java

If a pre-Lollipop devices receives a notification with a team that should be bolded, the app will crash from calling a method (`SpannableStringBuilder.append(CharSequence, Object, int)`) that's API 21+ only. That method is really just a convenient wrapper for some other methods, so I copied that method's source into our project, and that version is used instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/627)

Fixed issue caused by using an API 21+ method on all versions

---

android/src/main/java/com/thebluealliance/androidclient/datafeed/APIv2RequestInterceptor.java

Doing this forces App Engine to serve gzipped content. See https://cloud.google.com/appengine/kb/#compression
Personally I think it's weird that GAE checks both the User Agent and Accept-Encoding headers, but I read somewhere that their reasoning for doing so is because some clients improperly put gzip in the Accept-Encoding header even if it can't understand it, so it chooses to be extra safe with gzip.
Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/628)

Set okhttp user agent to 'gzip'

---

android/src/main/java/com/thebluealliance/androidclient/Constants.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/APIv2RequestInterceptor.java

Seems like 'gzip' only needs to be present in the user agent. Related to #628.
I put a partial user agent generated using the app's version name in constants, and then append '(gzip)' to the end of it in the request interceptor. Is that appropriate? Is that a decent user agent name?
http://googleappsdeveloper.blogspot.com/2011/12/optimizing-bandwidth-usage-with-gzip.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/629)

Set custom user agent with gzip for GAE

---

android/src/main/java/com/thebluealliance/androidclient/binders/ExpandableListViewBinder.java
android/src/main/java/com/thebluealliance/androidclient/binders/ListViewBinder.java
android/src/main/java/com/thebluealliance/androidclient/binders/MatchBreakdownBinder.java

If the binder receives invalid data, but there is already data bound,
that means the following case is most likely:
- There was data available in the local cache that we can display
- The network call returned an error/still is cached with an empty
value
This can happen when the user receives a push notification which writes
some data locally, but the remote endpoint has not had its cache
cleaered yet, causing the display to flicker between correct data and no
data view.
Fixes #638
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/645)

Tweak No Data binding logic

---

android/src/main/java/com/thebluealliance/androidclient/activities/SearchResultsActivity.java

No change in user-facing functionality. The support `SearchView` just handles some of the things we were doing manually before with the framework `SearchView`. This makes code a bit cleaner.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/658)

Moves search activity to use the support SearchView

---

android/src/main/java/com/thebluealliance/androidclient/binders/TeamInfoBinder.java
android/src/main/res/layout/fragment_team_info.xml
android/src/main/res/values/styles.xml

For teams with really long full team names (254, for instance), they are now limited to 3 lines at first, and ellipsized. Clicking the full name expands the view to show the full team name.
Fixes #233
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/665)

Makes the full team name view expandable

---

scripts/do_release.py

Because GitHub supports that now: https://github.com/blog/2144-gpg-signature-verification
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/666)

GPG Sign Release Tags

---

android/src/main/java/com/thebluealliance/androidclient/database/writers/YearsParticipatedWriter.java

Fixes this crash from the play store:
```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
Caused by: …
```

Null check setting team years participated

---

android/src/main/java/com/thebluealliance/androidclient/binders/MatchBreakdownBinder.java
android/src/main/java/com/thebluealliance/androidclient/views/breakdowns/MatchBreakdownView2016.java

Let the view return its status code so we can bind no data. This fixes
the issue where it would just show blank (although not the root cause)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/683)

Fix Bug With Breakdown NoData binding

---

android/src/main/java/com/thebluealliance/androidclient/fragments/event/EventInfoFragment.java
android/src/main/java/com/thebluealliance/androidclient/fragments/team/TeamInfoFragment.java
android/src/main/res/layout/fragment_event_info.xml
android/src/main/res/layout/fragment_team_info.xml

We don't need the extra 80dps of padding at the bottom of the team/event info view if myTBA is disabled and the FAB is not visible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/695)

Only show padding for the myTBA FAB if the FAB is visible

---

android/src/main/res/layout/list_item_team.xml

I missed this when I originally changed the team list to render with a `RecyclerView`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/698)

Added selectable item background to team list item

---

android/src/main/java/com/thebluealliance/androidclient/Interactions.java
android/src/main/java/com/thebluealliance/androidclient/binders/RecyclerViewBinder.java
android/src/main/java/com/thebluealliance/androidclient/fragments/EventListFragment.java
android/src/main/java/com/thebluealliance/androidclient/fragments/RecentNotificationsFragment.java
android/src/main/java/com/thebluealliance/androidclient/fragments/RecyclerViewFragment.java
android/src/main/java/com/thebluealliance/androidclient/fragments/TeamListFragment.java
android/src/main/java/com/thebluealliance/androidclient/fragments/district/DistrictEventsFragment.java
android/src/main/java/com/thebluealliance/androidclient/fragments/team/TeamEventsFragment.java
android/src/main/java/com/thebluealliance/androidclient/itemviews/EventItemView.java

Fixes an issue where clicking on an event in a team's event list opened the event view instead of the team@event view. This is my fault for not verifying behavior when I switched the event lists to use RecyclerView.
This better exploits the features of the adapter library we are using; namely, it moved view event (clicks, etc) handling out of the item and into a listener attached to the adapter. See [here](https://github.com/mrmans0n/smart-adapters#assigning-listeners) for reference.
Going forward, as we make the transition to RecyclerView, this is how we should do things. It generally makes list items more reusable. I'd like to write a class that lets us compose listeners so that we can reuse click listeners throughout the app while still having the option of using multiple listeners per …

Changed handling of clicks on event items

---

gce/gce2retrofit.jar
gce/gce_discovery.json
scripts/update_cloud_endpoints.sh
tbaMobile/src/main/java/com/appspot/tbatv_prod_hrd/Favorites.java
tbaMobile/src/main/java/com/appspot/tbatv_prod_hrd/Model.java
tbaMobile/src/main/java/com/appspot/tbatv_prod_hrd/Subscriptions.java
tbaMobile/src/main/java/com/appspot/tbatv_prod_hrd/Tbamobile.java
tbaMobile/src/main/java/com/appspot/tbatv_prod_hrd/TeamMedia.java

When we upgraded to retrofit2, there were some manual changes made to the GCE interfaces.
This pull updates the `gce2retrofit` jar (code on [this branch](https://github.com/phil-lopreiato/gce2retrofit/tree/gce-auth)) and returns to generated interfaces.
To update in the future, be sure to run `./scripts/update_cloud_endpoints.sh`
Towards #716 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/721)

Return to script-generated GCE Interfaces

---

.github/PULL_REQUEST_TEMPLATE

Looks like:
----------------------------
Summary: Add Phabricator-style pull request templates. The main change is to include a Test Plan, so we can see more screenshots/unit tests written. Phabricator also includes a field for "Reviewer" but I don't think we need that for our project (if we did, I'd default it to @the-blue-alliance/android). Should we also add a `CONTRIBUTING.md` file to explain the fields?
Issue Reference: Closes #739 
Test Plan: N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/740)

Add Pull Request Template

---

android/src/main/java/com/thebluealliance/androidclient/activities/ViewEventActivity.java
android/src/main/java/com/thebluealliance/androidclient/binders/EventInfoBinder.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/EventInfoSubscriber.java
android/src/test/java/com/thebluealliance/androidclient/subscribers/EventInfoSubscriberTest.java

**Summary**: Shows the event year as a subtitle in the Toolbar. This frees up a little bit of space in our already constrained Toolbar to show more of the event title.
**Issues Reference**: N/A
**Test Plan**: Updated existing tests to check the subtitle as well.
**Screenshot**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/749)

Show event year as subtitle in ViewEventActivity

---

android/src/main/res/layout/list_item_notification_alliance_selection.xml
android/src/main/res/values/styles_notifications.xml

**Summary:** Tightens up the padding on notification cards to increase information density
**Test Plan:** N/A
**Screenshots**
Before on the left, after on the right
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/751)

Make notification cards more dense

---

android/src/main/java/com/thebluealliance/androidclient/background/mytba/CreateSubscriptionPanel.java
android/src/main/java/com/thebluealliance/androidclient/fragments/mytba/MyTBASettingsFragment.java
android/src/main/res/layout/buffer_preference.xml

**Summary:** Instead of using an empty `Preference` to pad the bottom of the myTBA settings list, this now applies actual padding to the bottom of the list. This avoids the case of a random divider appearing in the list where it shouldn't (see screenshots).
**Test Plan:** N/A
Old (note the lone divider):
New:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/752)

Use actual padding for FAB padding instead of empty list item

---

android/src/main/java/com/thebluealliance/androidclient/activities/SearchResultsActivity.java
android/src/main/java/com/thebluealliance/androidclient/comparators/EventSortByTypeAndDateComparator.java
android/src/main/java/com/thebluealliance/androidclient/comparators/EventSortByTypeAndNameComparator.java
android/src/main/java/com/thebluealliance/androidclient/comparators/TeamSortByNumberComparator.java
android/src/main/java/com/thebluealliance/androidclient/database/ModelInflater.java
android/src/main/java/com/thebluealliance/androidclient/database/tables/EventsTable.java
android/src/main/java/com/thebluealliance/androidclient/database/tables/TeamsTable.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/deserializers/EventDeserializer.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/deserializers/TeamDeserializer.java
android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/AllianceSelectionNotification.java
android/src/main/java/com/thebluealliance/androidclient/helpers/EventHelper.java
android/src/main/java/com/thebluealliance/androidclient/helpers/EventTeamHelper.java
android/src/main/java/com/thebluealliance/androidclient/listitems/EventListElement.java
android/src/main/java/com/thebluealliance/androidclient/listitems/TeamListElement.java
android/src/main/java/com/thebluealliance/androidclient/models/Event.java
android/src/main/java/com/thebluealliance/androidclient/models/Team.java
android/src/main/java/com/thebluealliance/androidclient/renderers/EventRenderer.java
android/src/main/java/com/thebluealliance/androidclient/renderers/MyTbaModelRenderer.java
android/src/main/java/com/thebluealliance/androidclient/renderers/TeamRenderer.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/EventInfoSubscriber.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/MatchInfoSubscriber.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/TeamAtDistrictBreakdownSubscriber.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/TeamAtDistrictSummarySubscriber.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/TeamAtEventSummarySubscriber.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/TeamInfoSubscriber.java
android/src/test/java/com/thebluealliance/androidclient/datafeed/TBAApiTest.java
android/src/test/java/com/thebluealliance/androidclient/helpers/EventHelperTest.java
android/src/test/java/com/thebluealliance/androidclient/models/EventTest.java
android/src/test/java/com/thebluealliance/androidclient/models/TeamTest.java
android/src/test/java/com/thebluealliance/androidclient/subscribers/EventInfoSubscriberTest.java

**Summary:** I've been bugged for a long time by method names like `Event.getEventName()`. We know we're getting the *event* name because we're working with an `Event` object! This PR cleans things up by removing unneeded references to model type in get/set method names. This conveniently makes the internal model APIs more consistent. Zero change in functionality; this is all about aesthetics and consistency.
**Test Plan:** N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/753)

Updates API of model objects to have more consistent method names

---

android/src/main/java/com/thebluealliance/androidclient/database/tables/AwardsTable.java
android/src/main/java/com/thebluealliance/androidclient/database/tables/MatchesTable.java

**Summary:** The previous LIKE statement never actually worked. Because the JSON strings we were searching looked like `...["frc111","frc254","frc1114"]...`, matching against something like `frc111,` didn't actually work because of the quotes. This PR matches against `"frc111"` instead. This also avoids `frc111` inadvertently matching `frc1114`.
**Test Plan:** We really should find a way to test queries, because this has been broken for a long time and I only caught it because I happened to take a close look at this. That's beyond the scope of this PR, though.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/754)

[SQLite] Use quotes when matching team keys in JSON strings

---

scripts/travis-worker.sh

**Summary:** When travis fails with exit code 137, we should just allow, since it's not an actual failure, just a side effect of memory issues.
**Test Plan:** Intermittent, so it hopefully works...
**Screenshots:** N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/755)

Fix Travis Return Code Filter

---

android/src/main/AndroidManifest.xml
android/src/main/java/com/google/firebase/auth/GoogleAuthCredentialWrapper.java
android/src/main/java/com/thebluealliance/androidclient/auth/AuthProvider.java
android/src/main/java/com/thebluealliance/androidclient/auth/firebase/FirebaseAuthProvider.java
android/src/main/java/com/thebluealliance/androidclient/auth/firebase/MigrateLegacyUserToFirebase.java
android/src/main/java/com/thebluealliance/androidclient/auth/google/GoogleAuthProvider.java
android/src/main/java/com/thebluealliance/androidclient/di/components/MyTbaComponent.java
android/src/main/java/com/thebluealliance/androidclient/fragments/NavigationDrawerFragment.java

**Summary:** When a user upgrades to the newest version of the app (with an existing Google auth token), we'll recover and register for Firebase in the background
**Test Plan:** Downgraded to b26c91d015365c0008712f177c251bae738585b6 and then upgraded the app, verified my account appeared in the Firebase console
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/758)

Migrate users from legacy auth to Firebase

---

android/src/main/java/com/thebluealliance/androidclient/helpers/ConnectionDetector.java

**Summary:** Android has a bug where the service is created the first time with the
passed Context. The suggested workaround was to use ApplicationContext
See https://code.google.com/p/android/issues/detail?id=198852
**Issues Reference:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/759)

Get ConnectivityManager with an ApplicationContext

---

android/src/main/java/com/thebluealliance/androidclient/auth/AuthModule.java
android/src/main/java/com/thebluealliance/androidclient/auth/firebase/FirebaseAuthProvider.java
android/src/main/java/com/thebluealliance/androidclient/auth/firebase/MigrateLegacyUserToFirebase.java

**Summary:** Currently the app insta-crashes without the `google-secrets.json` file required by Firebase Authentication. This is because the library throws an exception when it can't find the file. This PR make it optional by catching the exception within DI and `FirebaseAuth` being `@Nullable` (enforced by Dagger)
**Test Plan:** Dagger enforces compile-time validity

Optional google-secrets.json

---

android/build.gradle
android/src/main/AndroidManifest.xml
android/src/main/java/com/thebluealliance/androidclient/activities/ViewTeamActivity.java
android/src/main/java/com/thebluealliance/androidclient/auth/AuthModule.java
android/src/main/res/values/strings.xml
build.gradle

**Summary:** 
- Adds runtime permission checks for WRITE_EXTERNAL_STORAGE in saving
team media suggestions
- Only request GET_ACCOUNTS for SDK <= 22 (it is not required for our
use case in 23+)
- Add a permissions dispatch library to make some of the runtime logic
simpler
- Do runtime checks for taking team media photos
- Target API 23
**Issues Reference:**  Closes #678
**Test Plan:** Ran fresh installs with this build on my phone (running 23+) and verifying the suggestion flow still worked. 
@nwalters512 Can you take a look and make sure this seems sane?

Target API 23

---

android/src/main/java/com/thebluealliance/androidclient/activities/settings/NotificationSettingsActivity.java
android/src/main/res/xml/notification_preferences.xml
android/src/main/res/xml/notification_preferences_lollipop.xml

**Summary:** 
I'm punting on the notification-sound-picker for lack of a way to make the standard dialog include the app's resources. There are more useful things to do than implement a custom sound picker.
But a tiny code improvement came out of the investigation: 
• The android:dependency preference attribute handles an if-enabled
dependency, obviating a bunch of code. It even handles the LED Color
dependency on both LED Enabled and Notifications Enabled (not that
the docs say so), fixing the handling of that dual dependency.
• android:title="Notification LED Color" wasn’t using its string
resource.
Tested in the emulator.
To reproduce the bug in the old code:
1. Open Settings.
2. Tap "Notification Settings".
3. Check "Enable Notifications" if it …

simplify the preference code and fix 2 minor bugs

---

android/src/androidTest/java/com/thebluealliance/androidclient/listitems/StatsListElementTest.java
android/src/main/java/com/thebluealliance/androidclient/listitems/StatsListElement.java

**Summary:** 
At MadTown 2017, the 2nd and 3rd robots have 8xxx and 9xxx numbers but
no names.
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
at com.thebluealliance.androidclient.listitems.StatsListElement.getView(StatsListElement.java:45)
```
#842
Manually tested.

Fix bug #842

---

android/src/androidTest/java/com/thebluealliance/androidclient/views/breakdowns/MatchBreakdownView2018Test.java
android/src/androidTest/resources/2018week0_qm1.json
android/src/main/java/com/thebluealliance/androidclient/binders/MatchBreakdownBinder.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/MatchBreakdownSubscriber.java
android/src/main/java/com/thebluealliance/androidclient/views/breakdowns/MatchBreakdownView2018.java
android/src/main/res/layout/match_breakdown_2018.xml
android/src/main/res/values-v21/strings_2018_breakdown.xml

**Summary:** 
Adds the match breakdown table for FRC POWER UP matches.
Closes: #846 
- Created unit test for match breakdown using local data
- Tested the breakdown on debug application, checking for layout inconsistencies, crashes, and leaks
- Compared data with official match data for accuracy

Added Match Breakdown Table for 2018

---

android/src/main/java/com/thebluealliance/androidclient/views/breakdowns/MatchBreakdownView2018.java

This OUGHT to fix the bug but the Breakdown tab says
“No match breakdown found”. Maybe that has to do with the EventBus messages?
```
03-16 01:03:24.615 7439-7439/com.thebluealliance.androidclient.development D/android.view.View: Match key clicked: 2018azfl_qm2
03-16 01:03:24.615 7439-7439/com.thebluealliance.androidclient.development W/GAv4: Discarding hit. Missing tracking id parameter: cd=com.thebluealliance.androidclient.activities.ViewEventActivity,a=661243983,sf=100.0,t=event,av=4.3.0+dirty,el=,ea=2018azfl_qm2,an=The Blue Alliance Debug,aid=4.3.0+dirty,tid=,ec=match_click
03-16 01:03:24.621 7439-7931/com.thebluealliance.androidclient.development V/FA: Activity paused, time: 3861058
03-16 01:03:24.627 7439-7439/com.thebluealliance.androidclient.development V/FA: onActivityCreated …
```

Fix #856: red vault data shown in blue vault fields

---

android/src/androidTest/java/com/thebluealliance/androidclient/views/MatchViewTest.java
android/src/main/java/com/thebluealliance/androidclient/listitems/MatchListElement.java
android/src/main/java/com/thebluealliance/androidclient/renderers/MatchRenderer.java
android/src/main/java/com/thebluealliance/androidclient/views/MatchView.java
android/src/main/res/drawable/match_rp_dot.xml
android/src/main/res/layout/list_item_match.xml

**Summary:** 
* Add dots to the Match view to display the amount of extra RP earned that match, mimicing the website.
* Parsing scoreBreakdown JSON slows down scrolling on older devices.
#865
Works on my phones
Tests fixed to not fail

Add Extra RP Dots

---

android/src/main/java/com/thebluealliance/androidclient/Utilities.java
android/src/test/java/com/thebluealliance/androidclient/UtilitiesTest.java

**Summary:** 
As reported in #841, team links with leading zeros (like those Chief Delphi provides for teams with < 4 digit team numbers) open up a blank page. TBA Web handles such links by stripping out the leading zeros, so this does this same.
#841 
Added unit tests for team link parsing.

Fix for opening team links with leading zeros

---

android/src/main/java/com/thebluealliance/androidclient/adapters/TeamAtEventFragmentPagerAdapter.java

**Summary:** 
Adds Media to the TeamAtEvent pages
* Add a TeamMediaFragment to the items of TeamAtEventFragmentPagerAdapter
* Refactor the TeamAtEventFragmentPagerAdapter slightly to match the style of ViewTeamFragmentPagerAdapter, which is a simpler style
Per #863, we know people use the Team @ Event pages much more than Team pages, so we should make sure the most useful information is displayed there. Indexing robot photos is a unique feature of TBA, so this adds the Media tab to the Team @ Event views.
Look at Team 254 @ Arizona 2018 . Observe a Media tab that matches the Team 254 2018 Media tab renders, although no media renders.
I am not sure why no media is rendering locally, either for imgur photos or for youtube videos. I tested with Team …

Add Media tab to Team at Event

---

android/src/main/java/com/thebluealliance/androidclient/datafeed/APICache.java

**Summary:** 
The logic for fetching events within a given month was funky in a few ways:
* It only kept events that were completely within the month (`monthStart <= eventStart && eventEnd < eventEnd`)
* This also actually would have excluded events ending on the last day of the month
* Both the month start and the month end were calculated with the correct year, month, and day, but using the current device time. This effectively meant that unless you were getting the events at precisely midnight, you wouldn't see any events starting on the first of the month. 
This new logic uses the correct time, and only checks that the event's start date lies within the month. If an event starts in July and ends in August, it is bucketed as a July event.
Fixes #870 
**Test …

Fix some offseason events not showing up

---

android/src/main/java/com/thebluealliance/androidclient/datafeed/combiners/TeamAtEventSummaryCombiner.java
android/src/main/java/com/thebluealliance/androidclient/fragments/teamAtEvent/TeamAtEventSummaryFragment.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/SubscriberModule.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/TeamAtEventSummarySubscriber.java
android/src/main/res/values/strings_team_at_event.xml
android/src/test/java/com/thebluealliance/androidclient/subscribers/TeamAtEventSummarySubscriberTest.java

**Summary:** 
When an event hasn't started yet, show something more useful than a totally blank screen in the team@event summary view
fixes https://github.com/the-blue-alliance/the-blue-alliance-android/issues/886
local

Improve team@event summary when event hasn't started

---

android/src/main/java/com/thebluealliance/androidclient/activities/ContributorsActivity.java

**Summary:** 
When I tried to open the contributors page in the settings tab, the app crashed and restarted. I experimented with this further and came to the conclusion that it was throwing an IllegalStateException because the AuthModule was not set. I believe that `ContributorsActivity.getComponent()` was not updated to reflect the changes in PR #884, causing the crash. When I added `.authModule(application.getAuthModule())` to the DaggerFragmentComponent builder in ContributorsActivity.java, it fixed the crash.
**Test Plan:**
Manual test.

Fix crash on ContributorsActivity load

---

android/src/main/java/com/thebluealliance/androidclient/gcm/GCMMessageHandler.java
android/src/main/java/com/thebluealliance/androidclient/imgur/ImgurSuggestionService.java

**Summary:** 
We weren't creating an `AuthModule` (see #884, also related #891) for the Imgur suggestion service and the GCM message handler components, so both were crashing.
This resolves both issues.
I'm not set up to test GCM notifications at the moment, but sending an FCM message from the Firebase console, or launching either of these services through other means all result in the same crash. After this fix, it does not crash.

Add auth module to imgur suggestion service and GCM message handler

---

android/src/main/java/com/thebluealliance/androidclient/TBAAndroid.java
android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/BaseNotification.java
android/src/main/res/values/strings_notification.xml

**Summary:** 
> Starting in Android 8.0 (API level 26), all notifications must be assigned to a channel.
So this means that notifications won't show for users on 8.0. This sets everything to a `mytba` channel
(my phone with 8.0, notifications triggered from script in the repo)

Add all notifications to default channel

---

scripts/do_release.py

Post to slack with the version, shortlog, and link to release. Saves me from doing it manually :)
Except this also moves the release script to python 3, which probably breaks it somehow, and I'll find out next release...

Auto-post releases to slack

---

android/src/main/AndroidManifest.xml
android/src/main/java/com/thebluealliance/androidclient/activities/ViewTeamActivity.java
android/src/main/res/xml/file_paths.xml

**Summary:** 
Resolves issue #894 by adding a FileProvider to make our picture capture compatible with Android 24+.
This also moves us from using the public Pictures directory with a "The Blue Alliance" subdirectory to just a "The Blue Alliance" directory within the external storage directory.
#894 
Tested up to the final confirmation step on a couple devices, including those running 5.0, 9.0, and 8.0.
N/A

Use a FileProvider for media suggestions

---

android/src/main/java/com/thebluealliance/androidclient/activities/MyTBASettingsActivity.java

**Summary:** 
#864 is right- our FAB animation was a bit too slow. This speeds it up a bit, making it a much more enjoyable experience.
#864 
N/A

Speed up FAB circular reveal to 350ms

---

android/src/main/java/com/thebluealliance/androidclient/comparators/AwardSortComparator.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/AwardsListSubscriber.java
android/src/test/java/com/thebluealliance/androidclient/comparators/AwardSortComparatorTest.java
android/src/test/java/com/thebluealliance/androidclient/subscribers/AwardsListSubscriberTest.java

**Summary:** 
Matches our awards sorting to web's.
#834 
Added unit tests for sort order.

Match awards sorting to web's sorting

---

android/src/main/java/com/thebluealliance/androidclient/gcm/GCMMessageHandler.java
scripts/test_notification.py

Long story.
Mainly, this is a reserved key in FCM that wasn't in GCM, so we see random failures.

[notification] Don't use message_type key in payloads

---

build.gradle
libTba/build.gradle

**Summary:** 
We can use many Java 8 language features (like lambdas) thanks to the Android Gradle Plugin's desugaring. We no longer need retrolambda (but it wasn't actually being applied anyway, so I'm just removing dead code).
There really wasn't much of a change here, but everything still compiles and seems to run fine.

Set compatibility level to Java 8, remove retrolambda

---

android/src/main/java/com/thebluealliance/androidclient/binders/EventInfoBinder.java

Fix Chief Delphi link for seeing photos for an event (see changes from https://github.com/the-blue-alliance/the-blue-alliance-ios/pull/420)

Fix URL for viewing Event photos on Chief Delphi

---

android/build.gradle
android/src/main/java/com/thebluealliance/androidclient/binders/MatchBreakdownBinder.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/MatchBreakdownSubscriber.java
android/src/main/java/com/thebluealliance/androidclient/views/breakdowns/MatchBreakdownView2020.java
android/src/main/res/drawable/breakdown2020_inner_goal.xml
android/src/main/res/drawable/breakdown2020_low_goal.xml
android/src/main/res/drawable/breakdown2020_outer_goal.xml
android/src/main/res/layout/match_breakdown_2020.xml
android/src/main/res/values/strings_score_breakdown.xml

**Summary:** 
Adding breakdown view for 2020 scoring.
There's no official data for 2020 available yet, so this diff yolos it, but puts it behind a feature flag so we can easily test come week 0.

2020 Score Breakdowns

---

android/src/main/java/com/thebluealliance/androidclient/adapters/EventsByWeekFragmentPagerAdapter.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/APICache.java
android/src/main/java/com/thebluealliance/androidclient/fragments/EventListFragment.java
android/src/main/java/com/thebluealliance/androidclient/fragments/EventsByWeekFragment.java
android/src/main/java/com/thebluealliance/androidclient/models/EventWeekTab.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/EventTabSubscriber.java
android/src/test/java/com/thebluealliance/androidclient/fragments/EventListFragmentTest.java
android/src/test/java/com/thebluealliance/androidclient/subscribers/EventTabSubscriberTest.java

This will make the tab construction logic more resilient.
Specifically, this fixes https://github.com/the-blue-alliance/the-blue-alliance-android/issues/937 because there's a late in the season preseason event the same logical week as the first official event. Which meant the app would group them together.
The new way groups by tab label, which should make things better

Rewrite Event Tab Creation To Be Better

---

android/src/main/AndroidManifest.xml
android/src/main/java/com/thebluealliance/androidclient/di/components/NotificationComponent.java
android/src/main/java/com/thebluealliance/androidclient/gcm/GCMBroadcastReceiver.java
android/src/main/java/com/thebluealliance/androidclient/gcm/GCMMessageHandler.java
android/src/test/java/com/thebluealliance/androidclient/TestTbaAndroid.java
android/src/test/java/com/thebluealliance/androidclient/gcm/TestGCMBroadcastReceiver.java
scripts/test_notification.py

This should fix crahes like 
```
Caused by java.lang.IllegalStateException
Not allowed to start service Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x1000010 pkg=com.thebluealliance.androidclient cmp=com.thebluealliance.androidclient/.gcm.GCMMessageHandler (has extras) }: app is in background uid UidRecord{ca22e23 u0a206 RCVR bg:+6m20s802ms idle change:uncached procs:1 seq(0,0,0)}
```
Because newer versions of android are more strict about running things in the background

Run Notification Processing via JobScheduler API

---

android/src/main/java/com/thebluealliance/androidclient/gcm/GCMMessageHandler.java
android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/SummaryNotification.java
android/src/main/java/com/thebluealliance/androidclient/receivers/NotificationChangedReceiver.java
android/src/test/java/com/thebluealliance/androidclient/gcm/GCMMessageHandlerTest.java
android/src/test/java/com/thebluealliance/androidclient/gcm/GCMMessageHandlerWithMocks.java

Send summary notifications if there is more than one currently active
Do this properly, according to https://developer.android.com/training/notify-user/group

Fix summary notifications

---

android/src/main/java/com/thebluealliance/androidclient/listeners/SocialClickListener.java

**Summary:** 
Trying to tap on an event's location on Android 11+ currently results in a toast that says "No app can handle that request".
This is because Android 11 and above require applications that query other packages to declare what they want to query in the manifest with `<query>` tags. See [package visibility](https://developer.android.com/training/package-visibility) for more info on this change.
The only reason we used this was to check if our links could be handled before launching them. Just launching the intent and catching any resulting `ActivityNotFoundException` has the same effect, so that's the route I went to fix.
Tested current behavior on Android 12L, and it works now!
I also changed the `geo:` intents to some garbage text to test the not found …

Fix geo intents on Android 11+

---

android/src/main/AndroidManifest.xml
android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/UpcomingMatchNotification.java

**Summary:** 
Two pronged approach to fixing the upcoming match notifications without icons:
* Most immediate problem was a missing `FLAG_IMMUTABLE` on the webcast action intent.
* But this also adds a default notification icon and color for FCM when FCM itself is showing the intent (e.g. due to an app crash from a missing pending intent 😉 )
Resolves #965 
Tested locally by sending myself a notification in my dev TBA Firebase instance. I was able to easily recreate the broken upcoming match notification and see the crash. Now it works!

Fix notifications without icons

---

android/src/main/java/com/thebluealliance/androidclient/helpers/TeamHelper.java
android/src/test/java/com/thebluealliance/androidclient/helpers/TeamHelperTest.java

**Summary:** 
When trying to view a Team@Event page for a B team, the app crashes with
```
Caused by: java.lang.NumberFormatException: For input string: "114B"
at java.lang.Integer.parseInt(Integer.java:797)
at java.lang.Integer.parseInt(Integer.java:915)
at com.thebluealliance.androidclient.helpers.TeamHelper.getTeamNumber(TeamHelper.java:61)
```
Easy steps to reproduce:
1. Go to the 2023 Madtown Throwdown event page (Nov 10-12, 2023)
2. Go to the rankings tab
3. Expand 114B's rankings
4. Click "more"
5. 💣 💥 
To fix this we just need to adjust our `getTeamNumber()` logic to properly extract team numbers for B teams.
New unit test assertions for B teams, and confirmed the previously broken flow now works.
The summary tab isn't great, but the matches tab …

Fix for crash when viewing team@event for a B team

---

android/build.gradle
android/src/main/AndroidManifest.xml
android/src/main/java/com/thebluealliance/androidclient/activities/LaunchActivity.java
android/src/main/java/com/thebluealliance/androidclient/activities/MyTBAOnboardingActivity.java
android/src/main/java/com/thebluealliance/androidclient/activities/OnboardingActivity.java
android/src/main/java/com/thebluealliance/androidclient/activities/settings/NotificationSettingsActivity.java
android/src/main/java/com/thebluealliance/androidclient/activities/settings/SettingsActivity.java
android/src/main/java/com/thebluealliance/androidclient/adapters/MyTBAOnboardingPagerAdapter.java
android/src/main/java/com/thebluealliance/androidclient/auth/AuthModule.java
android/src/main/java/com/thebluealliance/androidclient/auth/AuthProvider.java
android/src/main/java/com/thebluealliance/androidclient/auth/firebase/FirebaseAuthProvider.java
android/src/main/java/com/thebluealliance/androidclient/auth/google/GoogleAuthProvider.java
android/src/main/java/com/thebluealliance/androidclient/gcm/GCMMessageHandler.java
android/src/main/java/com/thebluealliance/androidclient/mytba/MyTbaOnboardingController.java
android/src/main/java/com/thebluealliance/androidclient/views/MyTBAOnboardingViewPager.java
android/src/main/res/layout/mytba_onboarding_view_pager.xml
android/src/main/res/values/strings_onboarding.xml
android/src/main/res/values/strings_settings.xml
android/src/main/res/xml/notification_preferences.xml
android/src/main/res/xml/notification_preferences_tiramisu.xml
android/src/test/java/com/thebluealliance/androidclient/auth/firebase/FirebaseAuthProviderTest.java
android/src/test/java/com/thebluealliance/androidclient/gcm/GCMMessageHandlerTest.java

**Summary:** 
Breaking Changes:
- https://developer.android.com/about/versions/13/behavior-changes-13
- https://developer.android.com/about/versions/14/behavior-changes-14
The biggest thing is notification permissions being moved to a runtime thing. This means we need to extend the onboarding flow to include requesting the permission. Some other things:
- centralize the logic for login/etc in `MyTbaOnboardingController`, since there's two entry points for this
- stop using `startActivityForResult` in favor of the new [`ActivityResultLauncher`](https://developer.android.com/training/basics/intents/result)
- skip posting notifications if we don't have the permission
- Add a toggle in settings to re-request the permission if needed

Changes for API 33 & 34

---

android/src/main/java/com/thebluealliance/androidclient/helpers/MatchHelper.java
android/src/test/java/com/thebluealliance/androidclient/helpers/MatchHelperTest.java

**Summary:** 
I can't believe nobody actively reported this (or that I didn't notice it in the crash logs before)...
The app's match key validation doesn't handle set numbers with two digits, so it crashes
We get this crash:
```
Fatal Exception: java.lang.IllegalArgumentException
Invalid match key 2023cmptx_sf11m1
com.thebluealliance.androidclient.fragments.match.MatchInfoFragment.onCreate (MatchInfoFragment.java:6) 
```
Added some tests to cover this

Fix Match Key Validation for Double Elim SFs

---

android/src/main/java/com/thebluealliance/androidclient/fragments/EventsByWeekFragment.java
android/src/main/java/com/thebluealliance/androidclient/models/EventWeekTab.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/EventTabSubscriber.java
android/src/test/java/com/thebluealliance/androidclient/models/EventWeekTabTest.java
android/src/test/java/com/thebluealliance/androidclient/subscribers/EventTabSubscriberTest.java

**Summary:** 
Our previous "current" week calculation doesn't really work outside the regular season because we are comparing the current week number of the year to tabs that represent an entire month.
For example, if the season ends on "week 7" (let's ignore pre-season for the sake of this example), then the following month is "week 8" and two months later is "week 9". But going by the calendar, we are on like week 20 by that point. 
Instead, our `EventWeekTab` now represents a _range_ of actual calendar weeks so we can find the correct tab for the current week.
Fixes #981
New unit tests! 
Also confirmed November is now correctly selected by default instead of December ✅

Fix "current" week calculation outside the regular season

---

android/src/main/res/layout/match_breakdown_2019.xml

**Summary:** 
Cargo ship breakdowns were getting clipped on super small screens.
In a perfect world we would use a smarter layout that breaks to multiple lines, but I suspect not many folks are looking at 2019 scores anyway. So I just squeezed ~24dp out of the padding.
Fixes #898 

Squeeze a few more dp out of the cargo ship breakdowns

---

android/build.gradle
android/src/main/java/com/thebluealliance/androidclient/TbaAndroid.java

Since the min SDK is 24, it is no longer necessary to use the Multidex library.
See the following for more info: https://developer.android.com/build/multidex#mdex-on-l

Remove Multidex declaration
