the-blue-alliance/the-blue-alliance-android

android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/ScoreNotification.java
android/src/main/java/com/thebluealliance/androidclient/helpers/MatchHelper.java
android/src/main/java/com/thebluealliance/androidclient/models/Match.java
android/src/test/java/com/thebluealliance/androidclient/test/helpers/EventHelperTest.java
android/src/test/java/com/thebluealliance/androidclient/test/models/MatchTest.java

Refactor out Match hasTeam() to apply the fix everywhere.
Refactor out red/blue alliance/teams/score getters. (I almost made them instance methods but adjusting the exception-handling code would not be as local.)
Use the existing Match#hasBeenPlayed() method.

Fix #387 Incorrect team@event Summary Alliance Determination

---

android/build.gradle
android/src/main/java/com/thebluealliance/androidclient/activities/FABNotificationSettingsActivity.java
android/src/main/java/com/thebluealliance/androidclient/activities/GamedayActivity.java
android/src/main/java/com/thebluealliance/androidclient/activities/settings/MyTBAModelSettingsActivity.java
android/src/main/java/com/thebluealliance/androidclient/fragments/gameday/GamedayTickerFragment.java
android/src/main/java/com/thebluealliance/androidclient/views/ScrimInsetsFrameLayout.java
android/src/main/res/layout/activity_fab_notification_settings.xml
android/src/main/res/layout/activity_gameday.xml
android/src/main/res/layout/activity_mytba_model_settings.xml
android/src/main/res/layout/activity_navigation_drawer.xml
android/src/main/res/values-v21/dimens.xml
android/src/main/res/values/attrs.xml
android/src/main/res/values/dimens.xml

Switched to using the FAB from the Design Support Library. Also began the transition to using Snackbars instead of Toasts; so far this is limited to the success/fail/noop result of updating mytba model settings.

Design support library

---

android/src/main/java/com/thebluealliance/androidclient/fragments/mytba/MyFavoritesFragment.java
android/src/main/java/com/thebluealliance/androidclient/fragments/mytba/MySubscriptionsFragment.java
android/src/main/java/com/thebluealliance/androidclient/fragments/teamAtEvent/TeamAtEventStatsFragment.java
android/src/main/java/com/thebluealliance/androidclient/fragments/teamAtEvent/TeamAtEventSummaryFragment.java
android/src/main/res/values/strings.xml

Added some more "no data" messages and fixed an issue with the myTBA fav/sub lists

More no data views

---

android/src/main/java/com/thebluealliance/androidclient/datafeed/APICache.java

So the db calls happen on a background thread

Create Observables with Observable.create

---

.travis.yml
android/build.gradle
android/src/main/java/com/thebluealliance/androidclient/activities/MoreSearchResultsActivity.java
android/src/main/java/com/thebluealliance/androidclient/database/Database.java
build.gradle

Looks like we didn't update everything when we changed how search is done. This fixes bug #453.

Search bugfix

---

android/src/main/java/com/thebluealliance/androidclient/activities/FABNotificationSettingsActivity.java
android/src/main/java/com/thebluealliance/androidclient/activities/OnboardingActivity.java

Minor change that shouldn't affect too many people, but it's still a good behavior to have.

Onboarding will only show the login prompt if play services is available

---

android/build.gradle
android/src/main/java/com/thebluealliance/androidclient/binders/AbstractDataBinder.java
android/src/main/java/com/thebluealliance/androidclient/binders/BinderModule.java
android/src/main/java/com/thebluealliance/androidclient/binders/EventInfoBinder.java
android/src/main/java/com/thebluealliance/androidclient/binders/EventTabBinder.java
android/src/main/java/com/thebluealliance/androidclient/binders/ExpandableListViewBinder.java
android/src/main/java/com/thebluealliance/androidclient/binders/ListViewBinder.java
android/src/main/java/com/thebluealliance/androidclient/binders/TeamInfoBinder.java
android/src/main/java/com/thebluealliance/androidclient/binders/TeamTabBinder.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/DataConsumer.java
android/src/main/java/com/thebluealliance/androidclient/fragments/ExpandableListViewFragment.java
android/src/main/java/com/thebluealliance/androidclient/fragments/ListViewFragment.java
android/src/main/java/com/thebluealliance/androidclient/fragments/event/EventDistrictPointsFragment.java
android/src/main/java/com/thebluealliance/androidclient/fragments/event/EventInfoFragment.java
android/src/main/java/com/thebluealliance/androidclient/fragments/event/EventMatchesFragment.java
android/src/main/java/com/thebluealliance/androidclient/fragments/event/EventStatsFragment.java
android/src/main/java/com/thebluealliance/androidclient/fragments/team/TeamInfoFragment.java
android/src/main/java/com/thebluealliance/androidclient/fragments/team/TeamMediaFragment.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/BaseAPISubscriber.java
android/src/main/res/layout/fragment_team_info.xml

Starts with TeaminfoBinder and EventInfoBinder

Butter knife integration

---

android/src/main/java/com/thebluealliance/androidclient/activities/HomeActivity.java
android/src/main/res/values/strings.xml
android/src/main/res/values/strings_notification.xml

Instead of launching a separate activity, the recent notifications list is now shown in-place in the home activity, list most other top-level lists.
We should talk about if we want to do the same for game day.

Show notifications in home activity

---

android/src/main/java/com/thebluealliance/androidclient/datafeed/deserializers/APIStatusDeserializer.java
android/src/main/java/com/thebluealliance/androidclient/gcm/GCMMessageHandler.java
android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/EventDownNotification.java
android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/GenericNotification.java
android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/NotificationTypes.java
android/src/main/java/com/thebluealliance/androidclient/models/APIStatus.java
android/src/main/res/values/strings_notification.xml
android/src/test/java/com/thebluealliance/androidclient/datafeed/deserializers/APIStatusDeserializerTest.java
android/src/test/java/com/thebluealliance/androidclient/gcm/notifications/EventDownNotificationTest.java
android/src/test/java/com/thebluealliance/androidclient/notifications/GenericNotificationTest.java
android/src/test/resources/api_status.json
android/src/test/resources/notification_event_down.json
test_notification.py

Won't render yet, doing so should depend on https://github.com/the-blue-alliance/the-blue-alliance-android/pull/513

Admin Message Support

---

android/build.gradle

Uses a [nice trick](https://twitter.com/manidesto/status/669195097947377664) from Chris Banes to make it easier to bump the versions on the support libraries and play services.

Improves support lib/play services versioning

---

android/src/main/res/layout/activity_navigation_drawer.xml

Defaults info "snackbar" to be invisible

---

android/src/main/java/com/thebluealliance/androidclient/activities/GamedayActivity.java
android/src/main/java/com/thebluealliance/androidclient/activities/ViewEventActivity.java
android/src/main/java/com/thebluealliance/androidclient/adapters/ViewEventFragmentPagerAdapter.java
android/src/main/java/com/thebluealliance/androidclient/di/components/FragmentComponent.java
android/src/main/java/com/thebluealliance/androidclient/fragments/FirebaseTickerFragment.java
android/src/main/java/com/thebluealliance/androidclient/fragments/event/EventTickerFragment.java
android/src/main/res/drawable/firebase_filter_shadow.xml
android/src/main/res/layout/activity_gameday.xml
android/src/main/res/layout/fragment_firebase_ticker.xml
android/src/main/res/values/strings_firebase.xml

This improves the ticker experience across the app
* Ticker is decoupled from GamedayActivity
* Ticker appears as a tab in individual events
* Filtering is now done with a bottom button bar, instead of a FAB
* Ticker uses the NoDataView to warn of an empty ticker, Firebase error, no items matching filter, etc.
Screenshots of the new visual look:
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/540)

Changes to the Firebase ticker

---

android/src/main/java/com/thebluealliance/androidclient/background/firstlaunch/LoadTBAData.java

Fixes #538
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/555)

Catch RuntimeExceptions in initial load

---

android/src/main/java/com/thebluealliance/androidclient/Constants.java
android/src/main/java/com/thebluealliance/androidclient/renderers/MediaRenderer.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/MediaListSubscriber.java
android/src/main/java/com/thebluealliance/androidclient/types/MediaType.java
android/src/main/res/values/strings.xml
android/src/test/java/com/thebluealliance/androidclient/renderers/MediaRendererTest.java
android/src/test/java/com/thebluealliance/androidclient/subscribers/MediaListSubscriberTest.java
android/src/test/resources/media_frc254_2014.json
android/src/test/resources/media_imgur.json

Now that they exist, we need to display them!
Closes #553 
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/560)

Imgur Media Support

---

android/src/main/java/com/thebluealliance/androidclient/types/MediaType.java

So we don't have a yuuuuuuuuge amount of pixels
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/575)

Use scaled image sizes for imgur media

---

android/src/main/java/com/thebluealliance/androidclient/datafeed/status/TBAStatusController.java

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/576)

Only prompt version updates on prod builds

---

android/src/main/java/com/thebluealliance/androidclient/binders/EventInfoBinder.java

Was forgetting to show the container CardView...
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/580)

Show next/last match cards in event info

---

android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/AllianceSelectionNotification.java
android/src/main/res/layout/list_item_notification_alliance_selection.xml
android/src/main/res/layout/list_item_notification_awards_posted.xml

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/581)

Fix Alliance notification color

---

android/src/main/java/com/thebluealliance/androidclient/binders/EventInfoBinder.java

If the eventbus event doesn't give us anything, hide the container for
the views. This fixes the bug in the case where you firt load next/last
match while there are still matches to go, but then resume the activity
after the last match has been played. This will cause the last match
card to be "stale", still showing the old last match. Now we'll hide it
in that case to produce the proper output.
Additionally, check if ButterKnife is bound during the eventbus
callbacks, since we may be in a resume state where we haven't done so
yet. This will fix crashes trying to access a null view in the onEvent
method, which many execute before `updateData` does or before the
framework initially runs `bindViews`.
Fixes #585
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on …

Fix live event next/last match bugs

---

scripts/do_release.py

Adds dry run, don't duplicate builds needlessly, can wait for travis
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/595)

More Release Script Updates

---

android/src/main/java/com/thebluealliance/androidclient/background/firstlaunch/LoadTBAData.java

D'oh!
Fixes #598
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/614)

Fix logic error in LoadTBAData

---

android/src/main/java/com/thebluealliance/androidclient/binders/EventInfoBinder.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/EventInfoSubscriber.java
android/src/main/res/layout/fragment_event_info.xml
android/src/main/res/values/strings.xml
android/src/test/java/com/thebluealliance/androidclient/subscribers/EventInfoSubscriberTest.java

If there is more than one webcast available, open a chooser dialog to select which stream
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/603)

Add "View Webcast" button to Event Info

---

android/src/main/java/com/thebluealliance/androidclient/activities/ViewTeamActivity.java
build.gradle

Fixes #618
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/620)

Hide media snackbar on fab click

---

android/src/main/java/com/thebluealliance/androidclient/activities/HomeActivity.java

onPrepareOptionsMenu calls setSearchEnabled which calls invalidateOptionsMenu which calls onPrepareOptionsMenu which calls...
Oops ¯\_(ツ)_/¯
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/621)

Fixed very bad memory issue caused by pseudo-recursive framework calls

---

android/src/main/java/com/thebluealliance/androidclient/fragments/event/EventAwardsFragment.java
android/src/main/java/com/thebluealliance/androidclient/fragments/gameday/GamedayWebcastsFragment.java
android/src/main/java/com/thebluealliance/androidclient/listitems/WebcastListElement.java
android/src/main/res/layout/list_item_carded_webcast.xml

Fixes #602
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/635)

Fix webcast list styling

---

android/src/main/java/com/thebluealliance/androidclient/binders/MatchBreakdownBinder.java
android/src/main/java/com/thebluealliance/androidclient/fragments/match/MatchBreakdownFragment.java
android/src/main/java/com/thebluealliance/androidclient/models/Match.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/MatchBreakdownSubscriber.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/StatsListSubscriber.java
android/src/main/java/com/thebluealliance/androidclient/views/breakdowns/MatchBreakdownView2016.java
android/src/main/res/layout/match_breakdown_2016.xml
android/src/main/res/values/strings_2016_breakdown.xml
android/src/test/java/com/thebluealliance/androidclient/subscribers/MatchBreakdownSubscriberTest.java

- Show team numbers involved in the match
- Show ranking points earned (only for quals)
Closes #637 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/643)

Match Breakdown Updates

---

android/src/main/java/com/thebluealliance/androidclient/fragments/FirebaseTickerFragment.java

Fixes #639
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/644)

Handle errors from Firebase REST API

---

android/src/main/java/com/thebluealliance/androidclient/binders/EventInfoBinder.java
android/src/main/java/com/thebluealliance/androidclient/helpers/WebcastHelper.java

Fixes #640 
Fixes #641
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/646)

Other W4 crashes

---

android/build.gradle
android/src/main/java/com/thebluealliance/androidclient/activities/LaunchActivity.java
android/src/main/java/com/thebluealliance/androidclient/background/firstlaunch/LoadTBAData.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/APIv2RequestInterceptor.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/DatafeedModule.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/HttpModule.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/gce/GceModule.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/gce/TbaSuggestionController.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/maps/RetrofitResponseMap.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/retrofit/APIv2.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/retrofit/FirebaseAPI.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/retrofit/GitHubAPI.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/retrofit/LenientGsonConverterFactory.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/retrofit/LenientGsonRequestBodyConverter.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/retrofit/LenientGsonResponseBodyConverter.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/status/StatusRefreshService.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/status/TBAStatusController.java
android/src/main/java/com/thebluealliance/androidclient/imgur/ImgurModule.java
android/src/main/java/com/thebluealliance/androidclient/imgur/ImgurSuggestionService.java
build.gradle
libImgur/build.gradle
libImgur/src/main/java/com/thebluealliance/imgur/ImgurApi.java
tbaMobile/build.gradle
tbaMobile/src/main/java/com/appspot/tbatv_prod_hrd/Favorites.java
tbaMobile/src/main/java/com/appspot/tbatv_prod_hrd/Model.java
tbaMobile/src/main/java/com/appspot/tbatv_prod_hrd/Subscriptions.java
tbaMobile/src/main/java/com/appspot/tbatv_prod_hrd/Tbamobile.java
tbaMobile/src/main/java/com/appspot/tbatv_prod_hrd/TeamMedia.java

Should help with a few crashes we've been seeing in the Dev Console. And it's always good to be running the latest and greatest code?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/636)

Update okhttp to latest 3.2.0

---

android/src/main/java/com/thebluealliance/androidclient/models/BasicModel.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/TeamAtDistrictBreakdownSubscriber.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/TeamAtDistrictSummarySubscriber.java

Just add some safety checks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/648)

Fix Team@District No data

---

android/src/main/java/com/thebluealliance/androidclient/di/TBAAndroidModule.java
android/src/main/java/com/thebluealliance/androidclient/di/components/FragmentComponent.java
android/src/main/java/com/thebluealliance/androidclient/di/components/NotificationComponent.java
android/src/main/java/com/thebluealliance/androidclient/fragments/FirebaseTickerFragment.java
android/src/main/java/com/thebluealliance/androidclient/gcm/GCMMessageHandler.java
android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/CompLevelStartingNotification.java
android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/ScoreNotification.java
android/src/main/java/com/thebluealliance/androidclient/helpers/MatchHelper.java
android/src/main/java/com/thebluealliance/androidclient/models/FirebaseNotification.java
android/src/main/java/com/thebluealliance/androidclient/models/Match.java
android/src/main/java/com/thebluealliance/androidclient/models/StoredNotification.java
android/src/main/java/com/thebluealliance/androidclient/renderers/MatchRenderer.java
android/src/main/java/com/thebluealliance/androidclient/renderers/RendererModule.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/MatchInfoSubscriber.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/MatchListSubscriber.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/RecentNotificationsSubscriber.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/SubscriberModule.java
android/src/main/java/com/thebluealliance/androidclient/types/MatchType.java
android/src/main/res/values/strings.xml
android/src/main/res/values/strings_team_at_event.xml
android/src/test/java/com/thebluealliance/androidclient/helpers/MatchTypeTest.java
android/src/test/java/com/thebluealliance/androidclient/notifications/ScoreNotificationTest.java
android/src/test/java/com/thebluealliance/androidclient/renderers/MatchRendererTest.java
android/src/test/java/com/thebluealliance/androidclient/subscribers/MatchInfoSubscriberTest.java
android/src/test/java/com/thebluealliance/androidclient/subscribers/RecentNotificationsSubscriberTest.java

[do not merge]
Still todo:
Fixes #430
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/649)

Octofinal Support

---

android/src/main/java/com/thebluealliance/androidclient/renderers/MediaRenderer.java

Now shows proper thumbnail and accounts for url parameters correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/655)

Fix YouTube videos with timestamps

---

android/build.gradle
android/src/main/java/com/thebluealliance/androidclient/ViewUtilities.java
android/src/main/java/com/thebluealliance/androidclient/adapters/AnimatedRecyclerMultiAdapter.java
android/src/main/java/com/thebluealliance/androidclient/fragments/FirebaseTickerFragment.java
android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/ScheduleUpdatedNotification.java
android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/ScoreNotification.java
android/src/main/java/com/thebluealliance/androidclient/helpers/MatchHelper.java
android/src/main/java/com/thebluealliance/androidclient/models/BasicModel.java
android/src/main/java/com/thebluealliance/androidclient/models/Match.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/MatchListSubscriber.java
android/src/main/java/com/thebluealliance/androidclient/viewmodels/AllianceSelectionNotificationViewModel.java
android/src/main/java/com/thebluealliance/androidclient/viewmodels/AwardsPostedNotificationViewModel.java
android/src/main/java/com/thebluealliance/androidclient/viewmodels/BaseViewModel.java
android/src/main/java/com/thebluealliance/androidclient/viewmodels/CompLevelStartingNotificationViewModel.java
android/src/main/java/com/thebluealliance/androidclient/viewmodels/DistrictPointsUpdatedNotificationViewModel.java
android/src/main/java/com/thebluealliance/androidclient/viewmodels/GenericNotificationViewModel.java
android/src/main/java/com/thebluealliance/androidclient/viewmodels/ScheduleUpdatedNotificationViewModel.java
android/src/main/java/com/thebluealliance/androidclient/viewmodels/ScoreNotificationViewModel.java
android/src/main/java/com/thebluealliance/androidclient/viewmodels/TeamViewModel.java
android/src/main/java/com/thebluealliance/androidclient/viewmodels/UpcomingMatchNotificationViewModel.java
android/src/main/res/layout/fragment_firebase_ticker.xml
android/src/test/java/com/thebluealliance/androidclient/datafeed/TBAApiTest.java
android/src/test/java/com/thebluealliance/androidclient/notifications/ScheduleUpdatedNotificationTest.java

The big change here is that the ticker now uses RecyclerView to render itself. By (almost) default, that gives us nice animations for new items and updating the list after sorting.
This also adds some nice animations and crossfades to make the whole experience a little more polished.
I made a [YouTube video demonstrating the changes](https://www.youtube.com/watch?v=V47zw61RrWU).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/662)

Revamp firebase

---

android/src/main/java/com/thebluealliance/androidclient/fragments/FirebaseTickerFragment.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/664)

Firebase animation fix

---

android/src/main/java/com/thebluealliance/androidclient/activities/HomeActivity.java

Fixes #667
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/669)

Fix Crash with district list bounds

---

android/src/main/java/com/thebluealliance/androidclient/eventbus/LiveEventMatchUpdateEvent.java
android/src/main/java/com/thebluealliance/androidclient/firebase/AllianceAdvancementEvent.java
android/src/main/java/com/thebluealliance/androidclient/fragments/event/EventAlliancesFragment.java
android/src/main/java/com/thebluealliance/androidclient/listitems/AllianceListElement.java
android/src/main/java/com/thebluealliance/androidclient/models/Match.java
android/src/main/java/com/thebluealliance/androidclient/renderers/EventRenderer.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/AllianceListSubscriber.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/MatchListSubscriber.java
android/src/main/java/com/thebluealliance/androidclient/types/MatchType.java
android/src/main/java/com/thebluealliance/androidclient/types/PlayoffAdvancement.java
android/src/main/res/layout/list_item_alliance.xml
android/src/main/res/values/strings.xml
android/src/test/java/com/thebluealliance/androidclient/renderers/EventRendererTest.java
android/src/test/java/com/thebluealliance/androidclient/subscribers/AllianceListSubscriberTest.java
android/src/test/java/com/thebluealliance/androidclient/subscribers/MatchListSubscriberTest.java

Closes #653
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/668)

Show Playoff Advancement for Alliances

---

android/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/671)

Update spectrum to 0.2.1

---

android/build.gradle
code_coverage.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/682)

Fix code coverage reporting

---

build.gradle

Changelog: http://developer.android.com/tools/support-library/index.html

Update to Support Lib v23.3.0

---

android/build.gradle
build.gradle

To 2.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/674)

Update Dagger version

---

android/build.gradle
build.gradle

Changelogs:
https://github.com/ReactiveX/RxAndroid/blob/master/CHANGES.md
https://github.com/ReactiveX/RxJava/releases
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/676)

Update rxjava to v1.1.0

---

build.gradle

Changelog: https://github.com/google/gson/blob/master/CHANGELOG.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/675)

Update gson version to 2.6.2

---

android/src/main/java/com/thebluealliance/androidclient/fragments/match/MatchBreakdownFragment.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/MatchBreakdownSubscriber.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/MatchInfoSubscriber.java
android/src/main/java/com/thebluealliance/androidclient/views/breakdowns/MatchBreakdownView2016.java

So we don't hit the same endpoint twice
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/684)

Match Breakdown Shares data with MatchInfo

---

android/src/main/java/com/thebluealliance/androidclient/binders/ExpandableListViewBinder.java

Fixes #690
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/691)

Fixed issue with team media not displaying after changing years

---

android/src/main/java/com/thebluealliance/androidclient/binders/StatsListBinder.java

Fixes #685
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/693)

Fix stats list binder crash with null menu

---

android/src/main/java/com/thebluealliance/androidclient/listeners/PlayoffAdvancementClickListener.java
android/src/main/java/com/thebluealliance/androidclient/listitems/AllianceListElement.java
android/src/main/java/com/thebluealliance/androidclient/types/PlayoffAdvancement.java
android/src/main/res/layout/list_item_alliance.xml
android/src/main/res/values/strings.xml

To explain the abbreviations.
Closes #670
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/701)

Show details for Alliance Playoff Advancement

---

android/src/main/java/com/thebluealliance/androidclient/fragments/EventsByWeekFragment.java

Yay for off-by-one errors!
Fixes #699
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/709)

Fix Week Selection Bugs

---

android/src/main/java/com/thebluealliance/androidclient/eventbus/EventAwardsEvent.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/AwardsListSubscriber.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/TeamAtEventSummarySubscriber.java
android/src/main/res/values/strings.xml
android/src/test/java/com/thebluealliance/androidclient/subscribers/AwardsListSubscriberTest.java
android/src/test/java/com/thebluealliance/androidclient/subscribers/TeamAtEventSummarySubscriberTest.java

Only shows if there is a nonzero number.
Fixes #687
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/708)

Show #Awards on Team@Event Summary

---

android/src/main/java/com/thebluealliance/androidclient/helpers/PitLocationHelper.java

Don't write code and ship features late at night :cry:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/718)

Fixed error with reading pit location from JSON

---

.travis.yml
scripts/travis-worker.sh

Summary: Run different travis items (checkstyle, unit tests, coverage) in different jobs. Should speed up builds.
Test Plan: Travis passes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/746)

Parallelize Travis Builds

---

.github/PULL_REQUEST_TEMPLATE
.github/PULL_REQUEST_TEMPLATE.md

To me personally, this looks better. Up for discussion though.
For reference, existing:
------------------------------------
Summary: Lorem ipsum dolor
Issues Reference: Lorem ipsum dolor
Test Plan: Lorem ipsum dolor
------------------------------------
And proposed: 
------------------------------------
**Summary:** Lorem ipsum dolor
**Issues Reference:** Lorem ipsum dolor
**Test Plan:** Lorem ipsum dolor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/750)

Bolded PR template items to make them more distinct

---

android/src/main/java/com/thebluealliance/androidclient/accounts/AccountController.java
android/src/main/java/com/thebluealliance/androidclient/auth/google/GoogleAuthProvider.java

Fix crashes when not present, fixes #768.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/769)

Make tba.properties optional

---

android/src/main/java/com/thebluealliance/androidclient/adapters/GamedayFragmentPagerAdapter.java
android/src/main/java/com/thebluealliance/androidclient/adapters/ViewEventFragmentPagerAdapter.java

**Summary:** They leak memory and nobody really used them anyway

Remove Firebase Tickers

---

android/build.gradle
android/src/main/java/com/thebluealliance/androidclient/Analytics.java
android/src/main/java/com/thebluealliance/androidclient/TBAAndroid.java
android/src/main/java/com/thebluealliance/androidclient/Utilities.java
android/src/main/java/com/thebluealliance/androidclient/accounts/AccountController.java
android/src/main/java/com/thebluealliance/androidclient/accounts/AccountModule.java
android/src/main/java/com/thebluealliance/androidclient/config/AppConfig.java
android/src/main/java/com/thebluealliance/androidclient/config/ConfigModule.java
android/src/main/java/com/thebluealliance/androidclient/config/LocalProperties.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/DatafeedModule.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/gce/GceModule.java
android/src/main/java/com/thebluealliance/androidclient/di/TBAAndroidModule.java
android/src/main/java/com/thebluealliance/androidclient/di/components/AuthComponent.java
android/src/main/java/com/thebluealliance/androidclient/di/components/DatafeedComponent.java
android/src/main/java/com/thebluealliance/androidclient/di/components/FragmentComponent.java
android/src/main/java/com/thebluealliance/androidclient/di/components/MyTbaComponent.java
android/src/main/java/com/thebluealliance/androidclient/di/components/NotificationComponent.java
android/src/main/java/com/thebluealliance/androidclient/di/components/SuggestionComponent.java
android/src/main/java/com/thebluealliance/androidclient/fragments/FirebaseTickerFragment.java
android/src/main/java/com/thebluealliance/androidclient/gcm/GcmController.java
android/src/main/java/com/thebluealliance/androidclient/gcm/GcmModule.java
android/src/main/java/com/thebluealliance/androidclient/imgur/ImgurSuggestionService.java
android/src/test/java/com/thebluealliance/androidclient/accounts/AccountControllerTest.java
android/src/test/java/com/thebluealliance/androidclient/di/MockConfigModule.java
android/src/test/java/com/thebluealliance/androidclient/di/MockDatafeedComponent.java
android/src/test/java/com/thebluealliance/androidclient/fragments/event/EventTickerFragmentTest.java
android/src/test/java/com/thebluealliance/androidclient/fragments/gameday/GamedayTickerFragmentTest.java
android/src/test/java/com/thebluealliance/androidclient/gcm/GcmControllerTest.java

**Summary:** Use [FirebaseRemoteConfig](https://firebase.google.com/docs/remote-config/) instead of `tba.properties` file.
**Test Plan:** Run and make sure app still works normally (no visible changes)

Integrate FirebaseRemoteConfig

---

android/src/main/java/com/thebluealliance/androidclient/database/Database.java
android/src/main/java/com/thebluealliance/androidclient/database/ModelInflater.java
android/src/main/java/com/thebluealliance/androidclient/database/tables/EventsTable.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/deserializers/EventDeserializer.java
android/src/main/java/com/thebluealliance/androidclient/helpers/EventHelper.java
android/src/main/java/com/thebluealliance/androidclient/models/Event.java
android/src/test/java/com/thebluealliance/androidclient/database/DatabaseTest.java

**Summary:** Main support for 2champs.
**Issues Reference:** Closes #787 
**Test Plan:** Ran the app, verified with screenshots above

[2champs] Render CMP name on tab headers

---

android/src/main/java/com/thebluealliance/androidclient/renderers/insights/EventInsights2016Renderer.java
android/src/main/java/com/thebluealliance/androidclient/renderers/insights/EventInsights2017Renderer.java
android/src/main/java/com/thebluealliance/androidclient/renderers/insights/EventInsightsRenderer.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/StatsListSubscriber.java
android/src/main/res/values/strings_2016_breakdown.xml
android/src/main/res/values/strings_2017_breakdown.xml
android/src/main/res/values/strings_score_breakdown.xml

**Summary:** Show this stuff: https://www.thebluealliance.com/event/2017week0#event-insights. This won't show the full auto/teleop breakdowns for all of the match stats because it's pretty hard to make it work and the information is already sense enough
**Test Plan:** Ran and verified correct data appears for 2017week0

Show 2017 Event Insights

---

android/build.gradle
android/src/main/java/com/thebluealliance/androidclient/TbaLogger.java
build.gradle

**Summary:** Hopefully this gives us greater visibility into what goes wrong

Integrate Fireabse Crash Reporting

---

android/src/main/java/com/thebluealliance/androidclient/TBAAndroid.java

Fix incorrect LeakCanary initialization

---

android/src/main/java/com/thebluealliance/androidclient/adapters/EventCursorAdapter.java

**Summary:** 
Fixed issue with date display when searching for more events
#871 
Reproduced steps in #871 to test that the dates changed. Also checked dates of other events (official and offseason) from various seasons to ensure no unintended changes resulted from my commits.

Fix "view more events" date issue

---

android/src/main/java/com/thebluealliance/androidclient/activities/SearchResultsActivity.java
android/src/main/java/com/thebluealliance/androidclient/listitems/EventListElement.java
android/src/main/java/com/thebluealliance/androidclient/listitems/TeamListElement.java

**Summary:** 
Use Renderers to render ListElements in SearchResultsActivity.
Fixes #878
`./gradlew testDevDebugUnitTest` has the same three test failures in my branch as in master.
Someone should confirm this is expected though.
Before:
After:

Show Team Locations in Search

---

android/src/main/java/com/thebluealliance/androidclient/activities/DatafeedActivity.java
android/src/main/java/com/thebluealliance/androidclient/activities/HomeActivity.java
android/src/main/java/com/thebluealliance/androidclient/activities/TeamAtDistrictActivity.java
android/src/main/java/com/thebluealliance/androidclient/activities/TeamAtEventActivity.java
android/src/main/java/com/thebluealliance/androidclient/activities/ViewDistrictActivity.java
android/src/main/java/com/thebluealliance/androidclient/activities/ViewEventActivity.java
android/src/main/java/com/thebluealliance/androidclient/activities/ViewMatchActivity.java
android/src/main/java/com/thebluealliance/androidclient/activities/ViewTeamActivity.java
android/src/main/java/com/thebluealliance/androidclient/auth/firebase/FirebaseAuthProvider.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/APIv3RequestInterceptor.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/MyTbaDatafeed.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/gce/GceAuthController.java
android/src/main/java/com/thebluealliance/androidclient/datafeed/gce/GceModule.java
android/src/test/java/com/thebluealliance/androidclient/datafeed/gce/GceAuthControllerTest.java

**Summary:** 
Parity with the ios app - get oauth tokens using the Firebase client library and ditch old legacy stuff
Fixes #877 
Fixes #860

Move mytba to Full Firebase Auth

---

libTba/gce/gce_discovery.json
libTba/src/main/java/com/appspot/tbatv_prod_hrd/Favorites.java
libTba/src/main/java/com/appspot/tbatv_prod_hrd/Model.java
libTba/src/main/java/com/appspot/tbatv_prod_hrd/Subscriptions.java
libTba/src/main/java/com/appspot/tbatv_prod_hrd/Tbamobile.java
libTba/src/main/java/com/appspot/tbatv_prod_hrd/TeamMedia.java

**Summary:** 
@fangeugene asked nicely
Tested mytba with prod build locally

Move to Client API

---

.travis.yml
android/build.gradle
android/src/main/java/com/thebluealliance/androidclient/TbaAndroid.java
android/src/test/java/com/thebluealliance/androidclient/TestTbaAndroid.java
build.gradle
spectrum/build.gradle

Target SDK 29 (Android Q) (and a bunch of dependencies along with it).
This unblocks goodies like:
- Android Q Dark Mode support (https://developer.android.com/guide/topics/ui/look-and-feel/darktheme)
- ???

target SDK 29

---

android/build.gradle
android/src/main/java/com/thebluealliance/androidclient/activities/HomeActivity.java
android/src/main/java/com/thebluealliance/androidclient/activities/settings/SettingsActivity.java
android/src/main/java/com/thebluealliance/androidclient/views/NoDataView.java
android/src/main/java/com/thebluealliance/androidclient/views/breakdowns/MatchBreakdownView2015.java
android/src/main/java/com/thebluealliance/androidclient/views/breakdowns/MatchBreakdownView2016.java
android/src/main/java/com/thebluealliance/androidclient/views/breakdowns/MatchBreakdownView2017.java
android/src/main/java/com/thebluealliance/androidclient/views/breakdowns/MatchBreakdownView2018.java
android/src/main/java/com/thebluealliance/androidclient/views/breakdowns/MatchBreakdownView2020.java
android/src/main/res/drawable/match_team_selector_blue.xml
android/src/main/res/drawable/match_team_selector_red.xml
android/src/main/res/layout/activity_mytba_settings.xml
android/src/main/res/layout/fragment_event_info.xml
android/src/main/res/layout/list_item_district.xml
android/src/main/res/layout/list_item_event.xml
android/src/main/res/layout/list_item_match.xml
android/src/main/res/layout/list_item_model.xml
android/src/main/res/layout/list_item_ranking.xml
android/src/main/res/layout/list_item_team.xml
android/src/main/res/layout/match_breakdown_2015.xml
android/src/main/res/layout/match_breakdown_2016.xml
android/src/main/res/layout/match_breakdown_2017.xml
android/src/main/res/layout/match_breakdown_2018.xml
android/src/main/res/layout/match_breakdown_2019.xml
android/src/main/res/layout/match_breakdown_2020.xml
android/src/main/res/layout/no_data_view.xml
android/src/main/res/values-night/colors.xml
android/src/main/res/values/colors.xml
android/src/main/res/values/score_breakdown_styles.xml
android/src/main/res/values/styles.xml

**Summary:** 
Targeting Android Q lets us do this!

Support Dark Theme

---

android/build.gradle

let's see if this makes the tests more reliable?

try to fix robolectric

---

android/build.gradle
android/src/main/java/com/thebluealliance/androidclient/TbaLogger.java
android/src/test/java/com/crashlytics/android/Crashlytics.java
build.gradle

Since apparently the old thing was turned off in the last year

Migrate to firebase crashlytics

---

android/build.gradle
android/src/main/java/com/thebluealliance/androidclient/activities/settings/DevSettingsActivity.java
android/src/main/java/com/thebluealliance/androidclient/activities/settings/SettingsActivity.java
android/src/main/res/xml/dev_preference_link.xml
android/src/main/res/xml/dev_preferences.xml
android/src/main/res/xml/preferences.xml
android/src/test/java/com/crashlytics/android/Crashlytics.java

https://developer.android.com/guide/topics/ui/settings

Migrate to AndroidX Preferences

---

android/build.gradle
android/src/main/java/com/thebluealliance/androidclient/di/components/FragmentComponent.java
android/src/main/java/com/thebluealliance/androidclient/fragments/DatafeedFragment.java
android/src/main/java/com/thebluealliance/androidclient/subscribers/BaseAPISubscriber.java
android/src/main/java/com/thebluealliance/androidclient/tracing/TraceWrapper.java
android/src/main/java/com/thebluealliance/androidclient/tracing/TracingController.java
android/src/main/java/com/thebluealliance/androidclient/tracing/TracingModule.java
android/src/test/java/com/thebluealliance/androidclient/datafeed/framework/SubscriberTestController.java
android/src/test/java/com/thebluealliance/androidclient/di/MockFragmentComponent.java
android/src/test/java/com/thebluealliance/androidclient/di/MockTracingModule.java
build.gradle

https://firebase.google.com/docs/perf-mon

Add Firebase Performance Tracking

---

android/src/main/java/com/thebluealliance/androidclient/gcm/GCMMessageHandler.java
android/src/test/java/com/thebluealliance/androidclient/database/DatabaseMocker.java
android/src/test/java/com/thebluealliance/androidclient/di/MockNotificationComponent.java
android/src/test/java/com/thebluealliance/androidclient/di/MockTbaAndroidModule.java
android/src/test/java/com/thebluealliance/androidclient/gcm/GCMMessageHandlerTest.java
android/src/test/java/com/thebluealliance/androidclient/gcm/GCMMessageHandlerWithMocks.java
android/src/test/java/com/thebluealliance/androidclient/gcm/notifications/AllianceSelectionNotificationTest.java
android/src/test/java/com/thebluealliance/androidclient/gcm/notifications/AwardsPostedNotificationTest.java
android/src/test/java/com/thebluealliance/androidclient/gcm/notifications/CompLevelStartingNotificationTest.java
android/src/test/java/com/thebluealliance/androidclient/gcm/notifications/DistrictPointsUpdatedNotificationTest.java
android/src/test/java/com/thebluealliance/androidclient/gcm/notifications/GenericNotificationTest.java
android/src/test/java/com/thebluealliance/androidclient/gcm/notifications/ScheduleUpdatedNotificationTest.java
android/src/test/java/com/thebluealliance/androidclient/gcm/notifications/ScoreNotificationTest.java
android/src/test/java/com/thebluealliance/androidclient/gcm/notifications/UpcomingMatchNotificationTest.java

Refactor some of the GCM message processing code to make it more testable

Improved Notification Unit Tests

---

android/build.gradle
build.gradle
gradle/wrapper/gradle-wrapper.properties

- compile SDK --> 33
- gradle wrapper
- assorted library versions

Dependency Updates
